"""Deploy job, rollback, queueing, Caddy files, orphan cleanup and runtime logs against FakeDockerCli."""

import pytest

from app.config import get_settings
from app.crypto import encrypt_secret, sha256_hex
from app.models import ApiKey, App, Deployment, Job
from app.services import app_runner, deployments, jobs
from tests.apps_support import FAKE_SHA, FakeDockerCli, make_app, new_token


@pytest.fixture
def docker(tmp_path, monkeypatch):
    fake = FakeDockerCli()
    app_runner.set_docker(fake)
    monkeypatch.setattr(get_settings(), "caddy_apps_dir", str(tmp_path / "apps"))
    monkeypatch.setattr(get_settings(), "app_build_dir", str(tmp_path))
    yield fake
    app_runner.set_docker(None)


@pytest.fixture
def project(make_user, make_project):
    return make_project(make_user())


def deploy(db, app, **kw):
    dep, job = deployments.start_deployment(db, app, trigger="manual", user_id=None, **kw)
    db.commit()
    return dep, job


def caddy_file(app):
    path = deployments.apps_dir() / f"{app.id}.caddy"
    return path.read_text() if path.exists() else None


def test_deploy_sequence_and_env(db, docker, project, tmp_path):
    key = ApiKey(
        project_id=project.id,
        name="k",
        role="service",
        prefix="dpl_service_x",
        key_hash=sha256_hex("s"),
        secret_encrypted=encrypt_secret("dpl_service_secret"),
    )
    db.add(key)
    db.commit()
    token = new_token()
    docker.leak = token
    app = make_app(db, project, env={"NODE_ENV": "production"}, token=token, api_key_id=key.id)
    dep, job = deploy(db, app)
    assert dep.status == "queued" and job is not None and job.params == {"deployment_id": dep.id, "key": app.id}

    assert jobs.run_queued() == [(job.id, "succeeded")]
    db.expire_all()
    dep = db.get(Deployment, dep.id)
    app = db.get(App, app.id)
    assert dep.status == "live" and app.live_deployment_id == dep.id
    assert dep.commit_sha == FAKE_SHA and dep.commit_message == "Initial commit"
    assert dep.image_tag == f"deployer-app/{app.id}:{dep.id}"
    assert dep.container_name == f"deployer-app-shop-{dep.id[:8]}"
    assert docker.steps() == ["clone", "build", "rm", "run", "health", "reload"]
    assert docker.calls[0] == ("clone", "https://github.com/acme/shop", "main")
    assert docker.calls[3][1:] == (dep.container_name, dep.image_tag)
    assert docker.calls[4] == ("health", dep.container_name, 3000)
    container = docker.containers[dep.container_name]
    assert container["labels"] == {"deployer.app": app.id, "deployer.deployment": dep.id}
    assert container["env"] == {
        "NODE_ENV": "production",
        "PORT": "3000",
        "DEPLOYER_URL": "http://localhost:8080/v1",
        "DEPLOYER_PROJECT_ID": project.id,
        "DEPLOYER_API_KEY": "dpl_service_secret",
    }
    assert "==> Cloning" in dep.log and "==> Routing" in dep.log and "Done" in dep.log
    assert token not in dep.log and "***" in dep.log
    assert caddy_file(app) == (
        f"# apps/{app.id}.caddy - generated by Deployer, do not edit\n"
        f":{app.port} {{\n\treverse_proxy {dep.container_name}:3000\n}}\n"
    )
    assert "FROM node:22-alpine" in docker.dockerfiles[0] and "npm ci" in docker.dockerfiles[0]
    assert db.get(Job, job.id).result == {"deployment_id": dep.id, "status": "live"}


def test_second_deploy_supersedes_and_failed_start_keeps_previous(db, docker, project):
    app = make_app(db, project)
    first, _ = deploy(db, app)
    jobs.run_queued()
    docker.calls.clear()
    second, _ = deploy(db, app)
    jobs.run_queued()
    db.expire_all()
    first, second, app = db.get(Deployment, first.id), db.get(Deployment, second.id), db.get(App, app.id)
    assert (first.status, second.status, app.live_deployment_id) == ("superseded", "live", second.id)
    assert first.container_name not in docker.containers and second.container_name in docker.containers
    assert docker.steps() == ["clone", "build", "rm", "run", "health", "reload", "rm"]
    assert docker.calls[-1] == ("rm", first.container_name)
    assert second.container_name in caddy_file(app)

    # A container that never accepts connections: the previous deployment stays live.
    docker.calls.clear()
    docker.fail_at = "health"
    third, job = deploy(db, app)
    assert jobs.run_queued() == [(job.id, "failed")]
    db.expire_all()
    third, second, app = db.get(Deployment, third.id), db.get(Deployment, second.id), db.get(App, app.id)
    assert third.status == "failed" and "did not accept connections on port 3000" in third.error
    assert second.status == "live" and app.live_deployment_id == second.id
    assert third.container_name not in docker.containers and second.container_name in docker.containers
    assert docker.steps() == ["clone", "build", "rm", "run", "health", "logs", "rm"]
    assert "reload" not in docker.steps() and second.container_name in caddy_file(app)
    assert "hello from the app" in third.log


def test_build_failure_is_redacted(db, docker, project):
    token = new_token()
    docker.leak = token
    docker.fail_at = "build"
    app = make_app(db, project, token=token)
    dep, job = deploy(db, app)
    assert jobs.run_queued() == [(job.id, "failed")]
    db.expire_all()
    dep = db.get(Deployment, dep.id)
    assert dep.status == "failed" and "build failed" in dep.error
    assert token not in dep.error and token not in dep.log and token not in (db.get(Job, job.id).error or "")
    assert db.get(App, app.id).live_deployment_id is None and docker.containers == {}


def test_cancel_between_steps(db, docker, fake_redis, project):
    app = make_app(db, project)
    dep, job = deploy(db, app)
    docker.hooks["build"] = lambda: fake_redis.set(jobs.cancel_key(job.id), "1")
    assert jobs.run_queued() == [(job.id, "cancelled")]
    db.expire_all()
    assert db.get(Deployment, dep.id).status == "cancelled"
    assert "run" not in docker.steps() and docker.containers == {}


def test_rollback_reuses_the_image(db, docker, project):
    app = make_app(db, project)
    a, _ = deploy(db, app)
    jobs.run_queued()
    b, _ = deploy(db, app)
    jobs.run_queued()
    db.expire_all()
    docker.calls.clear()
    a = db.get(Deployment, a.id)
    c, job = deployments.rollback(db, db.get(App, app.id), a, user_id=None)
    db.commit()
    assert (c.trigger, c.rollback_of, c.image_tag, c.commit_sha) == ("rollback", a.id, a.image_tag, FAKE_SHA)
    assert jobs.run_queued() == [(job.id, "succeeded")]
    db.expire_all()
    c, b, app = db.get(Deployment, c.id), db.get(Deployment, b.id), db.get(App, app.id)
    assert c.status == "live" and b.status == "superseded" and app.live_deployment_id == c.id
    assert docker.steps() == ["rm", "run", "health", "reload", "rm"]
    assert docker.calls[1] == ("run", c.container_name, a.image_tag)


def test_queued_deployments_run_one_at_a_time(db, docker, project):
    app = make_app(db, project)
    first, job1 = deploy(db, app)
    second, job2 = deploy(db, app)
    assert job1 is not None and job2 is None and second.job_id is None
    done = jobs.run_queued()
    assert [status for _, status in done] == ["succeeded", "succeeded"]
    db.expire_all()
    first, second = db.get(Deployment, first.id), db.get(Deployment, second.id)
    assert (first.status, second.status) == ("superseded", "live") and second.job_id == done[1][0]
    assert docker.steps().count("clone") == 2


def test_sweep_starts_waiting_and_closes_dead(db, docker, project):
    app = make_app(db, project)
    waiting = Deployment(app_id=app.id, status="queued", trigger="manual", branch="main", log="")
    dead_job = jobs.enqueue(db, type="app.deploy", params={"key": app.id}, project_id=project.id)
    dead_job.status, dead_job.error = "failed", "worker died"
    dead = Deployment(app_id=app.id, status="queued", trigger="manual", branch="main", log="", job_id=dead_job.id)
    db.add_all([waiting, dead])
    db.commit()
    deployments.scheduler_tick(jobs.get_sessionmaker())
    db.expire_all()
    assert db.get(Deployment, dead.id).status == "failed" and db.get(Deployment, dead.id).error == "worker died"
    assert db.get(Deployment, waiting.id).job_id is not None
    assert jobs.run_queued()[0][1] == "succeeded"


def test_image_pruning_keeps_five(db, docker, project):
    app = make_app(db, project)
    ids = []
    for _ in range(7):
        dep, _ = deploy(db, app)
        jobs.run_queued()
        ids.append(dep.id)
    db.expire_all()
    tags = [db.get(Deployment, i).image_tag for i in ids]
    assert tags[:2] == [None, None] and all(tags[2:])
    assert docker.images == set(tags[2:])
    assert [c for c in docker.calls if c[0] == "rmi"] == [
        ("rmi", f"deployer-app/{app.id}:{ids[0]}"),
        ("rmi", f"deployer-app/{app.id}:{ids[1]}"),
    ]


def test_caddy_rendering_with_hostnames(db, docker, project):
    from app.models import Domain

    app = make_app(db, project, preset="static")
    dep, _ = deploy(db, app)
    jobs.run_queued()
    db.add(
        Domain(
            hostname="shop.example.com",
            zone_id="z",
            target_type="app",
            app_id=app.id,
            project_id=project.id,
            status="active",
        )
    )
    db.add(Domain(hostname="pending.example.com", zone_id="z", target_type="app", app_id=app.id, status="pending"))
    db.commit()
    job = jobs.enqueue(db, type="app.route", params={"app_id": app.id})
    db.commit()
    assert jobs.run_job(job.id) == "succeeded"
    db.expire_all()
    dep = db.get(Deployment, dep.id)
    text = caddy_file(app)
    assert text.count(f"reverse_proxy {dep.container_name}:80") == 2
    assert "http://shop.example.com:8081 {" in text and "pending.example.com" not in text
    assert (
        deployments.render_caddyfile("x", 8101, "c", 80, [])
        == "# apps/x.caddy - generated by Deployer, do not edit\n:8101 {\n\treverse_proxy c:80\n}\n"
    )


def test_orphans_and_remove_job(db, docker, project):
    app = make_app(db, project)
    dep, _ = deploy(db, app)
    jobs.run_queued()
    docker.containers["deployer-app-ghost-12345678"] = {"labels": {"deployer.app": "gone", "deployer.deployment": "x"}}
    docker.containers["deployer-app-shop-old"] = {"labels": {"deployer.app": app.id, "deployer.deployment": "nope"}}
    deployments.write_caddy_file("gone", "# stale\n")
    deployments.ensure_apps_dir()
    docker.calls.clear()
    deployments.scheduler_tick(jobs.get_sessionmaker())
    db.expire_all()
    assert set(docker.containers) == {db.get(Deployment, dep.id).container_name}
    assert not (deployments.apps_dir() / "gone.caddy").exists() and caddy_file(app)
    assert (deployments.apps_dir() / "_empty.caddy").exists()
    assert docker.steps() == ["rm", "rm", "reload"]

    docker.calls.clear()
    job = jobs.enqueue(db, type="app.remove", params={"app_id": app.id, "slug": app.slug})
    db.commit()
    assert jobs.run_job(job.id) == "succeeded"
    assert docker.containers == {} and docker.images == set() and caddy_file(app) is None
    assert docker.steps() == ["rm", "rmi", "reload"]


def test_runtime_logs_poll(db, docker, fake_redis, project):
    app = make_app(db, project)
    assert deployments.poll_logs(jobs.get_sessionmaker(), docker) == 0
    dep, _ = deploy(db, app)
    jobs.run_queued()
    docker.log_lines = [f"line {i}" for i in range(600)]
    assert deployments.poll_logs(jobs.get_sessionmaker(), docker) == 600
    lines = fake_redis.lrange(deployments.logs_key(app.id), 0, -1)
    assert len(lines) == 500 and lines[-1] == "line 599"
    db.expire_all()
    assert docker.calls[-1][1:] == (db.get(Deployment, dep.id).container_name, None)
    docker.log_lines = ["later"]
    deployments.poll_logs(jobs.get_sessionmaker(), docker)
    assert docker.calls[-1][2] is not None  # --since the previous poll
    assert fake_redis.lrange(deployments.logs_key(app.id), -1, -1) == ["later"]
    assert deployments.runtime_logs(app, 2)[0] == ["line 599", "later"]


def test_generate_dockerfile_presets(db, project):
    static = make_app(db, project, "s", preset="static")
    text = deployments.generate_dockerfile(static)
    assert "FROM nginx:1.27-alpine" in text and "try_files $uri $uri/ /index.html" in text
    assert "for d in dist build out public ." in text
    static.output_dir, static.build_command = "www", "make site"
    assert 'cp -r "www"/. /out/' in deployments.generate_dockerfile(
        static
    ) and "RUN make site" in deployments.generate_dockerfile(static)
    python = make_app(db, project, "p", preset="python", start_command="uvicorn main:app --port 8000")
    text = deployments.generate_dockerfile(python)
    assert "pip install --no-cache-dir -r requirements.txt" in text
    assert 'CMD ["sh", "-c", "uvicorn main:app --port 8000"]' in text and "ENV PORT=8000" in text
    assert deployments.generate_dockerfile(make_app(db, project, "d", preset="dockerfile", container_port=5000)) is None
    assert deployments.internal_port(static) == 80 and deployments.internal_port(python) == 8000


# --- database access (docs/DEPLOYMENTS.md "Database access") ------------------------------------


def _source(db, project, name, kind, config, **fields):
    from app.crypto import encrypt_json
    from app.models import DataSource

    ds = DataSource(
        project_id=project.id,
        name=name,
        kind=kind,
        engine="mariadb" if kind == "sql" else "mongodb",
        mode=fields.pop("mode", "managed"),
        database_name=config.get("database", "x"),
        config_encrypted=encrypt_json(config),
        **fields,
    )
    db.add(ds)
    db.commit()
    return ds


def test_database_env_and_network(db, docker, project):
    import secrets
    from urllib.parse import quote, unquote, urlsplit

    from app.models import Device, utcnow

    sql_pw = "p@ss:/#% " + secrets.token_hex(4)  # characters that must be URL-encoded
    mongo_pw = "m@/?" + secrets.token_hex(4)
    sql_config = {"host": "mariadb", "port": 3306, "username": "u_sql", "password": sql_pw, "database": "p_shop"}
    _source(db, project, "shop-db", "sql", sql_config)
    uri = "mongodb://" + "u_mongo:" + quote(mongo_pw, safe="") + "@mongodb:27017/p_docs?authSource=p_docs"
    mongo_config = {"uri": uri, "database": "p_docs", "username": "u_mongo", "password": mongo_pw}
    _source(db, project, "Docs Store", "nosql", mongo_config)
    _source(db, project, "old", "sql", {"database": "gone"}, deleted_at=utcnow())
    _source(db, project, "ext", "sql", {"host": "db.example.com", "database": "ext"}, mode="external")
    device = Device(name="pi", owner_id=project.owner_id, roles=["database_host"], token_hash=secrets.token_hex(32))
    db.add(device)
    db.commit()
    _source(db, project, "edge", "sql", {"database": "edge"}, device_id=device.id)

    # Off by default: no network join, no variables.
    app = make_app(db, project, env={"DEPLOYER_DB_SHOP_DB_HOST": "override"})
    dep, _ = deploy(db, app)
    jobs.run_queued()
    db.expire_all()
    env = docker.containers[db.get(Deployment, dep.id).container_name]["env"]
    assert "connect" not in docker.steps() and [k for k in env if k.startswith("DEPLOYER_DB_")] == [
        "DEPLOYER_DB_SHOP_DB_HOST"
    ]

    app = db.get(App, app.id)
    app.database_access = True
    db.commit()
    docker.calls.clear()
    dep, _ = deploy(db, app)
    jobs.run_queued()
    db.expire_all()
    dep = db.get(Deployment, dep.id)
    assert dep.status == "live", dep.error
    assert docker.steps() == ["clone", "build", "rm", "run", "connect", "health", "reload", "rm"]
    assert docker.calls[4] == ("connect", "deployer_backend", dep.container_name)
    env = docker.containers[dep.container_name]["env"]
    assert env["DEPLOYER_DB_SHOP_DB_HOST"] == "override"  # the app's own variable wins
    assert (env["DEPLOYER_DB_SHOP_DB_PORT"], env["DEPLOYER_DB_SHOP_DB_USER"]) == ("3306", "u_sql")
    assert (env["DEPLOYER_DB_SHOP_DB_PASSWORD"], env["DEPLOYER_DB_SHOP_DB_DATABASE"]) == (sql_pw, "p_shop")
    sql = urlsplit(env["DEPLOYER_DB_SHOP_DB_URL"])
    assert (sql.scheme, sql.hostname, sql.port, sql.path, sql.username) == (
        "mysql",
        "mariadb",
        3306,
        "/p_shop",
        "u_sql",
    )
    assert "@" not in sql.password and unquote(sql.password) == sql_pw
    mongo = urlsplit(env["DEPLOYER_DB_DOCS_STORE_URL"])
    assert (mongo.scheme, mongo.hostname, mongo.port, mongo.path) == ("mongodb", "mongodb", 27017, "/p_docs")
    assert unquote(mongo.password) == mongo_pw and mongo.query == "authSource=p_docs&directConnection=true"
    assert env["DEPLOYER_DB_DOCS_STORE_DATABASE"] == "p_docs"
    assert not any(k.startswith(("DEPLOYER_DB_OLD_", "DEPLOYER_DB_EXT_", "DEPLOYER_DB_EDGE_")) for k in env)
    assert "Data source 'edge' is on a host device and is not reachable from apps" in dep.log
    assert "Connected to the project's databases network" in dep.log
    assert "DEPLOYER_DB_SHOP_DB_PASSWORD" in dep.log
    assert sql_pw not in dep.log and mongo_pw not in dep.log

    # Rollback of an app with database access joins the network too.
    docker.calls.clear()
    rb, _ = deployments.rollback(db, app, dep, user_id=None)
    db.commit()
    jobs.run_queued()
    db.expire_all()
    assert db.get(Deployment, rb.id).status == "live"
    assert ("connect", "deployer_backend", db.get(Deployment, rb.id).container_name) in docker.calls


def test_env_prefix():
    assert deployments.env_prefix("shop-db") == "DEPLOYER_DB_SHOP_DB_"
    assert deployments.env_prefix("Main Store.v2") == "DEPLOYER_DB_MAIN_STORE_V2_"
