import pytest
from sqlalchemy.dialects import mysql, postgresql

from app.errors import ApiError
from app.services import schema_ops

MY = mysql.dialect()
PG = postgresql.dialect()


def spec(**kw):
    base = {
        "name": "orders",
        "columns": [
            {"name": "id", "type": "BIGINT UNSIGNED", "primary_key": True, "auto_increment": True},
            {
                "name": "user_id",
                "type": "bigint unsigned",
                "nullable": False,
                "references": {"table": "users", "column": "id", "on_delete": "cascade"},
            },
            {"name": "total", "type": "DECIMAL(10,2)", "default": "0.00"},
            {"name": "status", "type": "VARCHAR(20)", "default": "new order", "unique": False},
            {"name": "code", "type": "CHAR(36)", "unique": True},
        ],
        "timestamps": True,
    }
    base.update(kw)
    return base


def test_build_create_table_mysql():
    [ddl] = schema_ops.build_create_table(spec(), MY)
    assert ddl.startswith("CREATE TABLE `orders` (")
    assert "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT" in ddl
    assert "`user_id` BIGINT UNSIGNED NOT NULL" in ddl
    assert "`total` DECIMAL(10,2) NULL DEFAULT 0.00" in ddl
    assert "`status` VARCHAR(20) NULL DEFAULT 'new order'" in ddl
    assert "`code` CHAR(36) NULL UNIQUE" in ddl
    assert "`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP" in ddl
    assert "ON UPDATE CURRENT_TIMESTAMP" in ddl
    assert "PRIMARY KEY (`id`)" in ddl
    assert "FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE" in ddl
    assert ddl.endswith("ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci")


def test_build_create_table_postgres():
    s = spec()
    s["columns"][0]["type"] = "BIGINT"
    s["columns"][1]["type"] = "bigint"
    s["columns"][4]["type"] = "UUID"
    statements = schema_ops.build_create_table(s, PG)
    ddl = statements[0]
    assert ddl.startswith('CREATE TABLE "orders" (')
    assert '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL' in ddl
    assert '"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP' in ddl
    assert "ENGINE" not in ddl
    assert statements[1] == 'CREATE INDEX "ix_orders_user_id" ON "orders" ("user_id")'


@pytest.mark.parametrize(
    "bad",
    [
        {"name": "orders; DROP TABLE users"},
        {"columns": [{"name": "id`", "type": "INT"}]},
        {"columns": [{"name": "id", "type": "INT); DROP TABLE x; --"}]},
        {"columns": [{"name": "id", "type": "INT", "default": "x'); DROP TABLE y; --"}]},
        {"columns": [{"name": "id", "type": "TEXT", "auto_increment": True}]},
        {"columns": [{"name": "a", "type": "INT"}, {"name": "A", "type": "INT"}]},
        {"columns": [{"name": "id", "type": "INT", "references": {"table": "u sers", "column": "id"}}]},
        {"columns": [], "timestamps": False},
        {"columns": [{"name": "created_at", "type": "DATETIME"}], "timestamps": True},
    ],
)
def test_build_create_table_rejects_bad_input(bad):
    with pytest.raises(ApiError) as err:
        schema_ops.build_create_table(spec(**bad), MY)
    assert err.value.status_code == 422


def test_type_allowlists():
    for t in (
        "INT",
        "int(11)",
        "BIGINT UNSIGNED",
        "varchar(255)",
        "DECIMAL(10, 2)",
        "TEXT",
        "JSON",
        "DATETIME(6)",
        "TIMESTAMP",
        "BOOLEAN",
        "UUID",
        "CHAR(36)",
        "LONGBLOB",
        "DOUBLE",
    ):
        schema_ops.check_type(t, "mysql")
    for t in (
        "SERIAL",
        "BIGINT",
        "TEXT",
        "JSONB",
        "UUID",
        "TIMESTAMP WITH TIME ZONE",
        "TIMESTAMPTZ",
        "BYTEA",
        "NUMERIC(12,4)",
        "DOUBLE PRECISION",
        "TEXT[]",
        "CHARACTER VARYING(40)",
    ):
        schema_ops.check_type(t, "postgresql")
    for t in ("JSONB", "ENUM('a')", "INT UNSIGNED; DROP", "VARCHAR(255) CHARACTER SET latin1"):
        with pytest.raises(ApiError):
            schema_ops.check_type(t, "mysql")


def test_render_default():
    assert schema_ops.render_default("CURRENT_TIMESTAMP", MY) == "CURRENT_TIMESTAMP"
    assert schema_ops.render_default("uuid()", PG) == "gen_random_uuid()"
    assert schema_ops.render_default(True, MY) == "TRUE"
    assert schema_ops.render_default(5, MY) == "5"
    assert schema_ops.render_default("-1.5", MY) == "-1.5"
    assert schema_ops.render_default("hello world", MY) == "'hello world'"
    with pytest.raises(ApiError):
        schema_ops.render_default("it's", MY)
    with pytest.raises(ApiError):
        schema_ops.render_default("a\\b", MY)


def test_normalize_validator():
    assert schema_ops.normalize_validator(None) is None
    wrapped = schema_ops.normalize_validator({"bsonType": "object", "required": ["a"]})
    assert wrapped == {"$jsonSchema": {"bsonType": "object", "required": ["a"]}}
    kept = schema_ops.normalize_validator({"$jsonSchema": {"bsonType": "object"}})
    assert kept == {"$jsonSchema": {"bsonType": "object"}}
    with pytest.raises(ApiError) as err:
        schema_ops.normalize_validator({"$where": "sleep(1000)"})
    assert err.value.code == "forbidden_operator"


def test_collection_names():
    schema_ops.check_collection_name("users")
    schema_ops.check_collection_name("audit.events")
    for bad in ("system.users", "1abc", "a$b", "", "x" * 200):
        with pytest.raises(ApiError):
            schema_ops.check_collection_name(bad)
