// Deployer logo: drawn in code so the app, the tray icon and Deployer.ico (generated by build.ps1)
// share one definition. C# 5 / .NET Framework 4.x only.
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;

namespace DeployerSetup
{
    public static class Logo
    {
        public static readonly Color Top = Color.FromArgb(0x63, 0x66, 0xF1);
        public static readonly Color Bottom = Color.FromArgb(0x43, 0x38, 0xCA);

        public static void Draw(Graphics g, RectangleF r)
        {
            SmoothingMode oldSmoothing = g.SmoothingMode;
            g.SmoothingMode = SmoothingMode.AntiAlias;
            float radius = r.Width * 0.24f;
            using (GraphicsPath path = RoundedRect(r, radius))
            using (LinearGradientBrush brush = new LinearGradientBrush(
                new PointF(r.Left, r.Top), new PointF(r.Right, r.Bottom), Top, Bottom))
            {
                g.FillPath(brush, path);
            }

            float s = r.Width;
            float stroke = s <= 20 ? s * 0.13f : s * 0.095f;
            using (Pen pen = new Pen(Color.White, stroke))
            {
                pen.StartCap = LineCap.Round;
                pen.EndCap = LineCap.Round;
                pen.LineJoin = LineJoin.Round;
                // Up arrow (deploy) over a base line.
                PointF[] chevron = new PointF[]
                {
                    new PointF(r.Left + s * 0.31f, r.Top + s * 0.47f),
                    new PointF(r.Left + s * 0.50f, r.Top + s * 0.28f),
                    new PointF(r.Left + s * 0.69f, r.Top + s * 0.47f)
                };
                g.DrawLines(pen, chevron);
                g.DrawLine(pen, r.Left + s * 0.50f, r.Top + s * 0.30f, r.Left + s * 0.50f, r.Top + s * 0.60f);
                g.DrawLine(pen, r.Left + s * 0.29f, r.Top + s * 0.73f, r.Left + s * 0.71f, r.Top + s * 0.73f);
            }
            g.SmoothingMode = oldSmoothing;
        }

        public static GraphicsPath RoundedRect(RectangleF r, float radius)
        {
            GraphicsPath path = new GraphicsPath();
            float d = Math.Min(radius * 2, Math.Min(r.Width, r.Height));
            if (d <= 0.5f)
            {
                path.AddRectangle(r);
                return path;
            }
            path.AddArc(r.Left, r.Top, d, d, 180, 90);
            path.AddArc(r.Right - d, r.Top, d, d, 270, 90);
            path.AddArc(r.Right - d, r.Bottom - d, d, d, 0, 90);
            path.AddArc(r.Left, r.Bottom - d, d, d, 90, 90);
            path.CloseFigure();
            return path;
        }

        public static Bitmap Render(int size)
        {
            Bitmap bmp = new Bitmap(size, size, PixelFormat.Format32bppArgb);
            using (Graphics g = Graphics.FromImage(bmp))
            {
                g.Clear(Color.Transparent);
                g.PixelOffsetMode = PixelOffsetMode.HighQuality;
                float inset = size >= 48 ? size * 0.04f : 0f;
                Draw(g, new RectangleF(inset, inset, size - inset * 2, size - inset * 2));
            }
            return bmp;
        }

        /// <summary>Builds a multi-size .ico: 32-bit DIB frames, plus a PNG frame for 256 px.</summary>
        public static byte[] BuildIco(int[] sizes)
        {
            byte[][] images = new byte[sizes.Length][];
            for (int i = 0; i < sizes.Length; i++)
            {
                using (Bitmap bmp = Render(sizes[i]))
                {
                    images[i] = sizes[i] >= 256 ? ToPng(bmp) : ToDib(bmp);
                }
            }
            using (MemoryStream ms = new MemoryStream())
            using (BinaryWriter w = new BinaryWriter(ms))
            {
                w.Write((ushort)0);
                w.Write((ushort)1);
                w.Write((ushort)sizes.Length);
                int offset = 6 + 16 * sizes.Length;
                for (int i = 0; i < sizes.Length; i++)
                {
                    w.Write((byte)(sizes[i] >= 256 ? 0 : sizes[i]));
                    w.Write((byte)(sizes[i] >= 256 ? 0 : sizes[i]));
                    w.Write((byte)0);
                    w.Write((byte)0);
                    w.Write((ushort)1);
                    w.Write((ushort)32);
                    w.Write(images[i].Length);
                    w.Write(offset);
                    offset += images[i].Length;
                }
                for (int i = 0; i < sizes.Length; i++) w.Write(images[i]);
                w.Flush();
                return ms.ToArray();
            }
        }

        static byte[] ToPng(Bitmap bmp)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                bmp.Save(ms, ImageFormat.Png);
                return ms.ToArray();
            }
        }

        static byte[] ToDib(Bitmap bmp)
        {
            int size = bmp.Width;
            int maskStride = ((size + 31) / 32) * 4;
            using (MemoryStream ms = new MemoryStream())
            using (BinaryWriter w = new BinaryWriter(ms))
            {
                w.Write(40);
                w.Write(size);
                w.Write(size * 2);
                w.Write((ushort)1);
                w.Write((ushort)32);
                w.Write(0);
                w.Write(size * size * 4 + maskStride * size);
                w.Write(0);
                w.Write(0);
                w.Write(0);
                w.Write(0);
                for (int y = size - 1; y >= 0; y--)
                {
                    for (int x = 0; x < size; x++)
                    {
                        Color c = bmp.GetPixel(x, y);
                        w.Write(c.B);
                        w.Write(c.G);
                        w.Write(c.R);
                        w.Write(c.A);
                    }
                }
                w.Write(new byte[maskStride * size]);
                w.Flush();
                return ms.ToArray();
            }
        }
    }
}
